# Generated by Django 2.2 on 2019-04-28 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic_info', '0001_initial'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageHalfInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.CharField(max_length=16, verbose_name='产品编号')),
                ('pro_type', models.CharField(default='半成品', max_length=16, verbose_name='类型')),
                ('pro_count', models.IntegerField(default=0, verbose_name='数量')),
                ('pro_unit_cost', models.FloatField(default=0.0, verbose_name='成本')),
                ('pro_unit_price', models.FloatField(default=0.0, verbose_name='标准零售价')),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '半成品信息',
                'verbose_name': '半成品信息',
                'db_table': 'syc_storage_half_info',
            },
        ),
        migrations.CreateModel(
            name='StorageHalfOperateRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_operate_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('pro_id', models.CharField(max_length=16, verbose_name='产品编号')),
                ('pro_operate', models.IntegerField(choices=[(0, '出库'), (1, '入库'), (2, '调整'), (3, '退货'), (4, '回滚')], default=0, verbose_name='操作类型')),
                ('pro_old_count', models.IntegerField(default=0, verbose_name='原数量')),
                ('pro_change_count', models.IntegerField(default=0, verbose_name='变化数量')),
                ('pro_new_count', models.IntegerField(default=0, verbose_name='最终数量')),
            ],
            options={
                'verbose_name_plural': '半成品库存操作记录',
                'verbose_name': '半成品库存操作记录',
                'db_table': 'syc_storage_half_operate_record',
            },
        ),
        migrations.CreateModel(
            name='StorageInOrderHalf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_total_count', models.IntegerField(default=0, verbose_name='总数')),
                ('in_created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('in_modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '半成品入库订单',
                'verbose_name': '半成品入库订单',
                'db_table': 'syc_storage_in_order_half',
            },
        ),
        migrations.CreateModel(
            name='StorageInOrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_total_count', models.IntegerField(default=0, verbose_name='总数')),
                ('in_created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('in_modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '成品入库订单',
                'verbose_name': '成品入库订单',
                'db_table': 'syc_storage_in_order_product',
            },
        ),
        migrations.CreateModel(
            name='StorageProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.CharField(max_length=16, verbose_name='产品编号')),
                ('pro_type', models.CharField(default='成品', max_length=16, verbose_name='类型')),
                ('pro_count', models.IntegerField(default=0, verbose_name='数量')),
                ('pro_unit_cost', models.FloatField(default=0.0, verbose_name='成本')),
                ('pro_unit_price', models.FloatField(default=0.0, verbose_name='标准零售价')),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '成品信息',
                'verbose_name': '成品信息',
                'db_table': 'syc_storage_product_info',
            },
        ),
        migrations.CreateModel(
            name='StorageProductOperateRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_operate_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('pro_id', models.CharField(max_length=16, verbose_name='产品编号')),
                ('pro_operate', models.IntegerField(choices=[(0, '出库'), (1, '入库'), (2, '调整'), (3, '退货'), (4, '回滚')], default=0, verbose_name='操作类型')),
                ('pro_old_count', models.IntegerField(default=0, verbose_name='原数量')),
                ('pro_change_count', models.IntegerField(default=0, verbose_name='变化数量')),
                ('pro_new_count', models.IntegerField(default=0, verbose_name='最终数量')),
            ],
            options={
                'verbose_name_plural': '成品库存操作记录',
                'verbose_name': '成品库存操作记录',
                'db_table': 'syc_storage_product_operate_record',
            },
        ),
        migrations.CreateModel(
            name='StorageOutOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('finish_time', models.DateTimeField(default=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'), verbose_name='完成时间')),
                ('price', models.FloatField(default=0.0, verbose_name='订单金额')),
                ('actual_price', models.FloatField(default=0.0, verbose_name='提货金额')),
                ('order_comment', models.CharField(max_length=256, verbose_name='订单备注')),
                ('translation_expense', models.FloatField(default=0.0, verbose_name='运费')),
                ('translation_comment', models.CharField(max_length=256, verbose_name='运费备注')),
                ('rebate', models.IntegerField(default=0, verbose_name='折扣')),
                ('payment_status', models.BooleanField(default=False, verbose_name='付款状态')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除')),
                ('customer_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_info.CustomerInfo', verbose_name='客户信息')),
                ('order_handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_info.UserInfo', verbose_name='用户信息')),
                ('purchase_order_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='purchase.PurchaseOrder', verbose_name='销售订单信息')),
            ],
            options={
                'verbose_name_plural': '出库订单',
                'verbose_name': '出库订单',
                'db_table': 'syc_storage_out_order',
            },
        ),
        migrations.CreateModel(
            name='StorageOutDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.CharField(max_length=16, verbose_name='产品编号')),
                ('pro_count', models.IntegerField(default=0, verbose_name='数量')),
                ('pro_price', models.FloatField(default=0.0, verbose_name='金额')),
                ('storage_out_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.StorageOutOrder', verbose_name='出库订单')),
            ],
            options={
                'verbose_name_plural': '出库订单详情',
                'verbose_name': '出库订单详情',
                'db_table': 'syc_storage_out_detail',
            },
        ),
        migrations.CreateModel(
            name='StorageInDetailProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.CharField(max_length=16, verbose_name='产品编号')),
                ('pro_count', models.IntegerField(default=0, verbose_name='数量')),
                ('product_in_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.StorageInOrderProduct', verbose_name='成品入库订单')),
            ],
            options={
                'verbose_name_plural': '成品入库订单详情',
                'verbose_name': '成品入库订单详情',
                'db_table': 'syc_storage_in_detail_product',
            },
        ),
        migrations.CreateModel(
            name='StorageInDetailHalf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.CharField(max_length=16, verbose_name='产品编号')),
                ('pro_count', models.IntegerField(default=0, verbose_name='数量')),
                ('half_in_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.StorageInOrderHalf', verbose_name='半成品入库订单')),
            ],
            options={
                'verbose_name_plural': '半成品入库订单详情',
                'verbose_name': '半成品入库订单详情',
                'db_table': 'syc_storage_in_detail_half',
            },
        ),
    ]
