# Generated by Django 2.2 on 2019-04-28 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic_info', '0001_initial'),
        ('purchase', '0001_initial'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementOutputDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_balance', models.FloatField(default=0.0, verbose_name='起始余额')),
                ('income', models.FloatField(default=0.0, verbose_name='收款')),
                ('balance', models.FloatField(default=0.0, verbose_name='余额')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('customer_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_info.CustomerInfo', verbose_name='客户信息')),
                ('refund_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.RefundOrder', verbose_name='退货单')),
                ('storage_out_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.StorageOutOrder', verbose_name='出库订单')),
            ],
            options={
                'verbose_name_plural': '对账单详情',
                'verbose_name': '对账单详情',
                'db_table': 'syc_statement_output_detail',
            },
        ),
        migrations.CreateModel(
            name='Cashflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_type', models.IntegerField(choices=[(0, '发货'), (1, '收款'), (2, '退货')], default=0, verbose_name='类型')),
                ('cash_change', models.FloatField(default=0.0, verbose_name='变动金额')),
                ('balance', models.FloatField(default=0.0, verbose_name='余额')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('customer_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_info.CustomerInfo', verbose_name='客户信息')),
                ('refund_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.RefundOrder', verbose_name='退货单')),
                ('storage_out_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.StorageOutOrder', verbose_name='出库订单')),
            ],
            options={
                'verbose_name_plural': '现金流',
                'verbose_name': '现金流',
                'db_table': 'syc_cashflow',
            },
        ),
    ]
