# Generated by Django 2.2 on 2019-04-28 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=128, verbose_name='地区')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('mobilephones', models.CharField(max_length=64, verbose_name='手机号')),
                ('address', models.CharField(max_length=512, verbose_name='地址')),
                ('phone', models.CharField(max_length=64, verbose_name='座机')),
                ('default_rebate', models.IntegerField(default=100, verbose_name='折扣')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name_plural': '客户信息',
                'verbose_name': '客户信息',
                'db_table': 'syc_customer_info',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64, verbose_name='用户名')),
                ('telephone_number', models.CharField(max_length=64, verbose_name='手机号')),
                ('level', models.IntegerField(default=0, verbose_name='用户等级')),
                ('comment', models.CharField(max_length=256, verbose_name='用户备注')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('sign_in_token', models.CharField(max_length=128, verbose_name='token')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name_plural': '用户信息',
                'verbose_name': '用户信息',
                'db_table': 'syc_user_info',
            },
        ),
        migrations.CreateModel(
            name='CustomerRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_count', models.IntegerField(default=0, verbose_name='订单数')),
                ('balance', models.FloatField(default=0.0, verbose_name='余额')),
                ('total_income', models.FloatField(default=0.0, verbose_name='总金额')),
                ('total_pro_count', models.IntegerField(default=0, verbose_name='总产品数')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=True, verbose_name='是否删除')),
                ('customer_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_info.CustomerInfo', verbose_name='客户信息')),
            ],
            options={
                'verbose_name_plural': '客户排名',
                'verbose_name': '客户排名',
                'db_table': 'syc_customer_rank',
            },
        ),
    ]
