# Generated by Django 2.2 on 2019-04-30 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrank',
            name='customer_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='basic_info.CustomerInfo', verbose_name='客户信息'),
        ),
    ]
